# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgressql/data
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    container_name: mnai_redis
    ports:
      - "6379:6379" # Expose Redis for debugging/monitoring if needed
    volumes:
      - redis_data:/data

  django-web:
   image: ghcr.io/rmaculan/medianai-compose:latest
   container_name: mnai_gunicorn
   depends_on:
     - db
     - redis # Django-web now depends on Redis for channel layers
   environment:
     DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
     DEBUG: ${DEBUG}
     DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
     DATABASE_ENGINE: ${DATABASE_ENGINE}
     DATABASE_NAME: ${DATABASE_NAME}
     DATABASE_USERNAME: ${DATABASE_USERNAME}
     DATABASE_PASSWORD: ${DATABASE_PASSWORD}
     DATABASE_HOST: ${DATABASE_HOST}
     DATABASE_PORT: ${DATABASE_PORT}
   env_file:
     - .env
   command: >
     sh -c "python manage.py migrate &&
            gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
   volumes:
     - media_data:/app/media

  daphne-web:
   image: ghcr.io/rmaculan/medianai-compose:latest
   container_name: mnai_daphne
   depends_on:
     - db
     - redis # Daphne-web now depends on Redis for channel layers
   environment:
     DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
     DEBUG: ${DEBUG}
     DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
     DATABASE_ENGINE: ${DATABASE_ENGINE}
     DATABASE_NAME: ${DATABASE_NAME}
     DATABASE_USERNAME: ${DATABASE_USERNAME}
     DATABASE_PASSWORD: ${DATABASE_PASSWORD}
     DATABASE_HOST: ${DATABASE_HOST}
     DATABASE_PORT: ${DATABASE_PORT}
   env_file:
     - .env
   command: >
     sh -c "daphne backend.asgi:application -b 0.0.0.0 -p 8001" # Daphne listens on port 8001
   volumes:
     - media_data:/app/media

  nginx:
    image: nginx:latest
    container_name: mnai_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/medianai.io.crt:/etc/ssl/certs/medianai.io.crt:ro # ssl certs
      - ./nginx/medianai.io.key:/etc/ssl/private/medianai.io.key:ro # ssh key
      - media_data:/app/media # Serve media files through Nginx
    depends_on:
      - django-web
      - daphne-web

volumes:
   postgres_data:
   media_data:
   redis_data: # Add redis_data volume
