name: Deploy Django App to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    environment: mnai
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/medianai:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/medianai:latest
          file: ./Dockerfile

      # If you want to use GitHub Container Registry, make sure you are logged in and have permission.
      # Otherwise, you can remove this step if it’s not needed:
      # - name: Build Docker image for GHCR
      #   run: |
      #     docker buildx build \
      #       --file ./Dockerfile \
      #       --tag ghcr.io/rmaculan/medianai-compose:${{ github.sha }} \
      #       --tag ghcr.io/rmaculan/medianai-compose:latest \
      #       .

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /medianai-compose
            docker-compose down || true
            docker-compose pull django-web
            docker-compose up -d --no-deps django-web
            echo "Deployment complete!"
